spring:
    datasource:
        driver-class-name:  com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/PB?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
        username: root
        password: root #uqANDpushingbarriers911@
        platform: mysql

    jpa:
        hibernate:
            ddl-auto: update
            show-sql: true
            dialect: org.hibernate.dialect.MySQLDialect

    servlet:
        multipart:
          max-file-size: 5MB
          max-request-size: 10MB
